<?php

$names = "Alina Anastasiya Angelina Andrian Anna Anna Maria Bozena Valery Vasilisa Veronica Victoria Faith Darina Daria Diana Evelyn Emily Eve Elizabeth Zlata Ivanna Ilona Iryna Karina Carolina Kateryna Lily Maria Marta Marian Milan Hope Natalia Oksana Alexandra Elena Olesya Olga Log Roksolana Salome Sofia Tatiana Ulyana Baptism Julian Julia Justin Yana Yasmin Maria Anna Valentyna Olga Galyna Tatiana Hope Lyudmyla Elena Natalia Nina Love Kateryna Svetlana Lidia Faith Iryna Oksana Alexandra Rajisa Tamara Larysa Antonina Eugenia Anastasiya Alla Evdokia Zinaida Julia Natalia Sofia Victoria Marina Inna Zoya Barbarian Praskov'ja Claudia Lily Ulyana Stefania Yaroslav Lesya Kseniya Vasilisa Euphrasinia Daria Matrona Log Nelia Melania Paraskevi Elizabeth Ivanna Joan Myroslava Stepaniya Pelagia Pelagia Taisiya Marfa Eve Maya Neonila Alina Pavlina Emily Taisa Alena Vita Angela Theodore Olesya Stanislav Margarita Yana Yevhen Tamil Zinovy Baptism Dina Ruslan Agatha Stepanida Gunn Rosalia Feodosiya Linate Marta Leonid Arina Thecla Julia Bronislaw Yanina Darya Elizaveta Neal Marian Raisa Aglaia Azalea Adelaide Adeline Aynur Alsanna Almira Amalia Amir Aneliya Nor Apollonia Arianna Aurora Athena Bozena Vanessa Velyana Vinora Vlasta Gabriel Dzhanika Dzvenyslava Dinara Esli Esther Eteri Yeseniya Fun Zlatoslava Zoiana Ilaria John Iustyniya Yin Tsyun Kamil Kvitoslava Linda Louisa Raspberry Malik Marie Maryam Melissa Milad Milan Milolika Measure Mirabella Monica Naina Nicole Olivia Paulina Pollyanna Ryan Sabrina Slavo Slad Sogdiana Tanvi Timatini Haya Tsvitana Junius Yardana Gums Victoria Viktoria Vika Natalia Natali Karolina Carolina Caroline Karoline";

$adjectives = "alive dead backward forward beatufil ugly big small blunt sharp boring interesting bright dark broad narrow clean dirty clever stupid closed open cool warm cruel kind dangerous safe dark light colour deep shallow difficult easy dry wet early late fake real fast slow fat thin gentle fierce good bad happy sad hard soft heavy light weight high low hot cold ill well innocent guilty long short length loose tight loud soft voice low high modern ancient noisy quiet normal strange old people young old things new outgoing shy poor rich right answer wrong right direction left rough smooth short people ю tall sour sweet strong weak terrible wonderful far near cheap expensive abacterial abandoned abashed abatised abbatial abdicant abdominal abdominous abducent abecedarian aberrant abiotic abject ablastemic ablative ablaze able abler abloom abluent abnormal abominable aboriginal aborning above abradant abroach abrupt absent absent absolute abstract abstruse absurd abundant abuzz acanthoid acarpous acatalectic acaudal acaulescent acid aggregate agricultural ahead air alienated alight all aloof ambiguous ambulant angry animal another aging any apple arm automatic autumn babbling baby back bad barred bengal big black blue bus caspian chatty cheap chic china circulatory clean cleanest contemporary conversable conversational crossed crossing culminant dark dated dear deep detached discharged dismissed distraught dry elegant elevated equal equivocal estranged fabulous fair farm fashionable fertile filthy fitting flippant fluent fluid fresh frigid gabby garrulous gossipy green high high flown highest homonymic homonymous horse illustrious impudent insolent italian junior last late latvian leaky light lingual linguistic lip liquid loquacious maroon mean medic medical medicinal mediterranean meridian mouthy movable moveable my narrative negative neglected newsy normative obnoxious old fashioned omnibus ousted overgrown overhead paramount private proactive probable prurient pulpy quality random real removed running ruthenian safe seductive shag simple slow small smart smash smashing social sombre sovereign speech stylish supreme suspended sweet talkative tall tea temperate terse thick thin tight tired top topmost towering transitional transitive unearthly uppermost upset upstream utmost verbal verbose violent virtual voluble weekly spoken wide widespread windy yellow yesterday young zoological zootechnic zootheistic zooty zootypic zulu zwinglian zygomorphic zymological zymotic";

$names = explode(" ", $names);
$adjectives = explode(" ", $adjectives);

$name = $names[rand(0, count($names)-1)];
$adj = $adjectives[rand(0, count($adjectives)-1)];
?>